ontime:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "data/warehouse/ontime.duckdb"
      threads: 4
    bq:
      type: bigquery
      method: oauth
      impersonate_service_account: dbt-runner@ontime-dp-yn24.iam.gserviceaccount.com
      project: ontime-dp-yn24
      dataset: ontime
      location: europe-west9
      threads: 4
      maximum_bytes_billed: 5000000000
